#!/bin/sh
# Xcode Cloud post-clone script
# Runs after repo clone, before package resolution and build.
# Required because TyFiWatch.xcodeproj is generated by xcodegen, not committed.
set -e

echo "==> Installing xcodegen..."
brew install xcodegen

echo "==> Generating Xcode project from project.yml..."
xcodegen generate

echo "==> Generated files:"
ls -la TyFiWatch.xcodeproj/
